// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdniv-tLPA3gCXzhWqcD6bAf50pt7jaU',
    appId: '1:297012917075:web:574deb8bec818f8321a7a6',
    messagingSenderId: '297012917075',
    projectId: 'popularfoamcenter-886ad',
    authDomain: 'popularfoamcenter-886ad.firebaseapp.com',
    storageBucket: 'popularfoamcenter-886ad.firebasestorage.app',
    measurementId: 'G-0KYSHMLGGB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATsL03ID0UyTVewrzheqVjcGbwDKguLOQ',
    appId: '1:297012917075:ios:6e0e3231e4282c7e21a7a6',
    messagingSenderId: '297012917075',
    projectId: 'popularfoamcenter-886ad',
    storageBucket: 'popularfoamcenter-886ad.firebasestorage.app',
    iosBundleId: 'com.rajarehman.dev.pfc',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATsL03ID0UyTVewrzheqVjcGbwDKguLOQ',
    appId: '1:297012917075:ios:6e0e3231e4282c7e21a7a6',
    messagingSenderId: '297012917075',
    projectId: 'popularfoamcenter-886ad',
    storageBucket: 'popularfoamcenter-886ad.firebasestorage.app',
    iosBundleId: 'com.rajarehman.dev.pfc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAentqhzKLMwjw3QLAYldj9sWErjllCVEA',
    appId: '1:297012917075:android:43288f40fa6aa8cd21a7a6',
    messagingSenderId: '297012917075',
    projectId: 'popularfoamcenter-886ad',
    storageBucket: 'popularfoamcenter-886ad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhdniv-tLPA3gCXzhWqcD6bAf50pt7jaU',
    appId: '1:297012917075:web:2d75bafc8e37a35f21a7a6',
    messagingSenderId: '297012917075',
    projectId: 'popularfoamcenter-886ad',
    authDomain: 'popularfoamcenter-886ad.firebaseapp.com',
    storageBucket: 'popularfoamcenter-886ad.firebasestorage.app',
    measurementId: 'G-YW3N0NQ523',
  );

}